version: "3"
services:
  backend_docs:
    build: ./backend_docs
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      VIRTUAL_HOST: backend.docs.test.kitty.xqe2011.cn
      LETSENCRYPT_HOST: backend.docs.test.kitty.xqe2011.cn

    networks:
      - default
      - web

  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mariadb-database:/var/lib/mysql
    ports:
      - 33066:3306
    environment:
      MARIADB_DATABASE: kitty
      MARIADB_USER: kitty
      MARIADB_PASSWORD: yeMAoinkpK6kVAKf
      MARIADB_ROOT_PASSWORD: HgwdJeLiIbAy0VFb
      KITTY_DA_USERNAME: "kitty-da"
      KITTY_DA_PASSWORD: "q64DV8oj2JImBLuV"
      
  backend:
    build: ./backend
    restart: always
    depends_on: 
      - mariadb
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      VIRTUAL_HOST: api.test.kitty.xqe2011.cn
      LETSENCRYPT_HOST: api.test.kitty.xqe2011.cn
      database.host: mariadb
      database.username: kitty
      database.password: yeMAoinkpK6kVAKf
      database.name: kitty
      secret: SzG0QKRUCna8fahUBoZfG8HqBO94NK9j
      debug: "true"
      api.url: https://api.test.kitty.xqe2011.cn
      files.url: https://cdn.test.kitty.xqe2011.cn
      files.upload.provider: qiniu
      files.providers.qiniu.scope: test-dgut-kitty-static
      files.providers.qiniu.upload.url: https://up-z2.qiniup.com
      files.providers.qiniu.access_key: ${QINIU_ACCESS_KEY}
      files.providers.qiniu.secret_key: ${QINIU_SECRET_KEY}
      wechat.miniprogram.appid: ${WECHAT_APP_ID}
      wechat.miniprogram.appsecret: ${WECHAT_APP_SECRET}
      wechat.auto_update_token: "false"
      
    networks:
      - default
      - web

networks: 
  web:
    external:
      name: web-gateway_web

volumes:
  mariadb-database: