version: "3"
services:
  backend_docs:
    build: ./backend_docs
    restart: always
    volumes:
      - /etc/timezone/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      VIRTUAL_HOST: backend.docs.release.kitty.xqe2011.cn
      LETSENCRYPT_HOST: backend.docs.release.kitty.xqe2011.cn

    networks:
      - default
      - web

  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - /etc/timezone/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mariadb-database:/var/lib/mysql
    ports:
      - 33077:3306
    environment:
      MARIADB_DATABASE: kitty
      MARIADB_USER: kitty
      MARIADB_PASSWORD: ${MARIADB_KITTY_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      KITTY_DA_USERNAME: "kitty-da"
      KITTY_DA_PASSWORD: ${MARIADB_DA_PASSWORD}
      
  backend:
    build: ./backend
    restart: always
    depends_on: 
      - mariadb
    volumes:
      - /etc/timezone/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      VIRTUAL_HOST: api.release.kitty.xqe2011.cn
      LETSENCRYPT_HOST: api.release.kitty.xqe2011.cn
      database.host: mariadb
      database.username: kitty
      database.password: ${MARIADB_KITTY_PASSWORD}
      database.name: kitty
      secret: ${SECRET}
      debug: "false"
      api.url: https://api.release.kitty.xqe2011.cn
      files.url: https://cdn.release.kitty.xqe2011.cn
      files.upload.provider: qiniu
      files.providers.qiniu.scope: release-dgut-kitty-static
      files.providers.qiniu.upload.url: https://up-z2.qiniup.com
      files.providers.qiniu.access_key: ${QINIU_ACCESS_KEY}
      files.providers.qiniu.secret_key: ${QINIU_SECRET_KEY}
      wechat.miniprogram.appid: ${WECHAT_APP_ID}
      wechat.miniprogram.appsecret: ${WECHAT_APP_SECRET}
      
    networks:
      - default
      - web

networks: 
  web:
    external:
      name: web-gateway_web

volumes:
  mariadb-database: